apiVersion: v1
kind: Secret
metadata:
    name: custom-secrets
type: Opaque
data:
    secretkey: a21neXNhI2Z6KzkoejEqPWMweWRyaml6ayo3c3RobTJnYTF6ND1eNjEkY3hjcThiJGw=
    mysqlrootpass: bmV3c3FscGFzc3dvcmQ=