apiVersion: v1
kind: Secret
metadata:
    name: custom-secrets
type: Opaque
data:
    secretkey: KmQqKXBeajErMCpkQDBja3BlbXBkI3IpJUBkNCVrNTIkKipnLTAqJSF1a29wKXVsc28=
    mysqlrootpass: bmV3c3FscGFzc3dvcmQ=
    