apiVersion: batch/v1
kind: CronJob
metadata:
  name: compliance-check
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: compliance-check
            image: nyuappsec/assign3-db:v0
            command: ["/bin/sh","/usr/local/cmd.sh"]
            env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: custom-secrets
                  key: mysqlrootpass

            - name: MYSQL_DATABASE
              value: GiftcardSiteDB
            volumeMounts:
            - name: mnt
              mountPath: /usr/local/cmd.sh
              subPath: file-from-cfgmap
          restartPolicy: Never
          volumes:
          - name: mnt
            configMap:
              name: nginx-cfgmap
              defaultMode: 0777